# Generated by Django 5.0.1 on 2025-04-23 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, verbose_name='单词')),
                ('translation', models.CharField(max_length=100, verbose_name='翻译')),
                ('image', models.ImageField(upload_to='flashcards/', verbose_name='图片')),
                ('pronunciation', models.FileField(blank=True, upload_to='pronunciations/', verbose_name='发音')),
                ('example', models.TextField(blank=True, verbose_name='例句')),
                ('language', models.CharField(choices=[('zh', '中文'), ('en', '英文')], max_length=2, verbose_name='语言')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '单词卡',
                'verbose_name_plural': '单词卡',
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mastered', models.BooleanField(default=False)),
                ('review_count', models.IntegerField(default=0)),
                ('last_reviewed', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcards.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '学习进度',
                'verbose_name_plural': '学习进度',
            },
        ),
    ]
