# Generated by Django 5.0.1 on 2025-04-27 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_word', models.CharField(max_length=100, verbose_name='英文单词')),
                ('chinese_translation', models.CharField(max_length=100, verbose_name='中文翻译')),
                ('example_sentence', models.TextField(blank=True, null=True, verbose_name='例句')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_reviewed', models.DateTimeField(auto_now=True, verbose_name='最后复习时间')),
                ('review_count', models.IntegerField(default=0, verbose_name='复习次数')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '单词卡',
                'verbose_name_plural': '单词卡',
                'ordering': ['-created_at'],
            },
        ),
    ]
